# Generated by Django 2.1.1 on 2018-09-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robots_title', models.CharField(max_length=100)),
                ('robots_description', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
    ]
