# Generated by Django 2.1.1 on 2018-09-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='robots_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(),
        ),
    ]
