# Generated by Django 2.1.1 on 2018-09-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_search', '0003_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('index', models.TextField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
