# Generated by Django 2.1.1 on 2018-09-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_search', '0004_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='size',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='word',
            new_name='search_text',
        ),
    ]
